version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
        environment:
          MOCHA_FILE: .~/junit/mocha/results.xml

    steps:
      - checkout
      - run: npm install
      - run: npm install mocha-junit-reporter # just for CircleCI
      - run: mkdir ~/junit
      - run: mkdir ~/junit/mocha
      - run:
          command: ./node_modules/mocha/bin/mocha test --reporter mocha-junit-reporter
          # environment:
          #   MOCHA_FILE: .~/junit/mocha/results.xml
          when: always
      - store_test_results:
          path: ~/junit/mocha
      - store_artifacts:
          path: ~/junit/mocha